### ISSUE TITLE
multirepo support

### ISSUE THREAD

**Issue by kangshung** [oprypin/mkdocs-literate-nav#16]
Hey, is it possible to use this plugin along with [multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin)? :) 

If so, do you have any tutorials on what's the best way to connect automatic gen files + literate nav + mkdocstrings + multirepo for multiple projects?

**Comment by oprypin** [comment]
I haven't checked those plugins together. And sorry, I don't intend to look into this.

**Comment by kangshung** [comment]
Ok, thank you very much for the answer.
