### ISSUE TITLE
Only SUMMARY.md works

### ISSUE THREAD

**Issue by majkinetor** [oprypin/mkdocs-literate-nav#2]
I tried it and README.md and other stuff do not work. 

I tried to not specify nav_file as doc mention defaults or specify README.md.

BTW,  you should document mention that `section-index` should come after this plugin in settings or it doesn't work

**Comment by oprypin** [comment]
The base claim appears to be not true to me.

If you take any working site with "SUMMARY.md" and change only that too "foo.md", also making sure to rename the file accordingly, it will still work. I just tried that.

Also README.md I'm using here and it works as well https://github.com/oprypin/crsfml/tree/master/docs/tutorials

If you wish to back up your claim, please produce a self-contained mkdocs site source (repository) that sees this behavior.

--- 

> BTW, you should document mention that section-index should come after this plugin in settings or it doesn't work

Right... I'll get to that

**Comment by oprypin** [comment]
The latter is addressed as https://github.com/oprypin/mkdocs-literate-nav/commit/fd23bda00402692ece9690c8b2ae70fe5471ae34 + https://github.com/oprypin/mkdocs-section-index/commit/145ce693fa86d950e602fc8f6eab1ea29c8be236 (neither included in a release yet)

**Comment by majkinetor** [comment]
> If you wish to back up your claim, please produce a self-contained mkdocs site source (repository) that sees this behavior.

OK, I will see too do that. Just wanted to confirm here first.
