### ISSUE TITLE
Question: literate-nav and fragments / query strings in --strict mode 

### ISSUE THREAD

**Issue by sn0wcat** [oprypin/mkdocs-literate-nav#24]
I am struggling with the use of literate-nav plugin together with --strict mode. 

Mkdocs is throwing an error as soon as I pass a fragment or a query string like this 

in nav.md
```markdown
* [Libraries](../apis.html?resourceType=Library%2CSDK)
* [Contact](documentation.md#contact)
```
I get warnings which are then converted to errors in --strict mode

```shell
WARNING  -  A relative path to 'apis.html?resourceType=Library%2CSDK' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'documentation.md#contact' is included in the 'nav' configuration, which is not found in the documentation files
```
Is there a way to tell to `mkdocs` or to `literate-nav` to ignore the fragments or querystrings in the links? I don't want to abandon `--strict` mode just yet...

**Comment by oprypin** [comment]
mkdocs-literate-nav just prepares a nav and hands it over to MkDocs (i.e. you could always write the same nav in mkdocs.yml and get the same outcome), and indeed MkDocs can't deal with this. The solution would have to be in MkDocs
