### ISSUE TITLE
Remove inferred-directory link use from the mkdocs INFO logging somehow?

### ISSUE THREAD

**Issue by danielloader** [oprypin/mkdocs-literate-nav#29]
Hey thanks for the plugin it's been great and the SUMMARY.md files have proven themselves flexible and powerful.

That being said it causes my mkdocs server dev server log to be full of entries such as:

```
INFO    -  Doc file 'development/v1/SUMMARY.md' contains an unrecognized relative link 'introduction/', it was left as is.
```

I've made use of [inferred-directory links](https://github.com/oprypin/mkdocs-literate-nav?tab=readme-ov-file#inferred-sub-directory) in the SUMMARY.md files but all these verbose INFO lines are hiding the more serious WARNING lines where pages are linked to missing pages.

Any advice would be welcome.

**Comment by oprypin** [comment]
See: https://github.com/oprypin/mkdocs-literate-nav/issues/28#issuecomment-1848397051

**Comment by oprypin** [comment]
I'm also aware of this as a general problem but got in too deep the last time I tried to comprehensively solve it
