### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by jwillmer** [oprypin/mkdocs-literate-nav#7]
Is there an option to open the referenced page in a new tab?

**Comment by oprypin** [comment]
This is not enough information

**Comment by jwillmer** [comment]
Sorry I will at more details below:

[This](https://github.com/RemoteCloud/public-documentation/blob/dev/mkdocs/docs/api/.pages) is the `.page` I'm referring to. As you can see it is referencing sub folders. If I build the static site with MKDoc the api folder looks like [this](https://github.com/RemoteCloud/public-documentation/tree/gh-pages/dev/api). It contains static websites not build by MKDocs. I would like to open these pages in a new window. Check out the public documentation and click on a [API documentation](https://developer.maranics.com/dev/api/) and I think you get why I like to open it in a separate window.

**Comment by oprypin** [comment]
This plugin doesn't provide any features that aren't possible to achieve by typing out the nav manually in MkDocs.  And this indeed isn't possible to achieve in MkDocs through the nav on its own.
Would be quite an easy new plugin to make, but this isn't the place to ask about it. Try https://github.com/mkdocs/mkdocs/discussions
